### ISSUE TITLE
Incorrect Label on the Loans Table

### ISSUE THREAD

**Issue by mendave** [bediniupi/Alma-print-slip#2]
The text of one of the field names gets replaced with the text "sorted ascending" or "sorted descending" for whichever column the loans are being sorted by. For instance, if the loans are being sorted by "Title" then the text "Title" will be replaced with "sorted ascending" on the slip. If the loans are being sorted by the due date, rather than saying "Due Date" it will say "sorted ascending." This only happens for the title of the column being used to sort the loans.

I have tried it with the Firefox extension, and the bookmarklet in both Firefox and Chrome and this issue persists across all of them.

**Comment by bediniupi** [comment]
Issue solved in version 1.1
